<?php

use Illuminate\Database\Seeder;

use App\Employee;
use App\Deductionitem;
use App\Employeededuction;

class EmployeesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    private function setDeductions($employee_id){

        $deductionitems = Deductionitem::get()->all();

        foreach ($deductionitems as $deductionitem)
        {
            $employeededuction = new Employeededuction;
            $employeededuction->employee_id = $employee_id;
            $employeededuction->deductionitem_id = $deductionitem->id;
            $employeededuction->amount = $deductionitem->defaultamount;
            $employeededuction->status = "Inactive";
            $employeededuction->save();
        }

    }

    public function run()
    {
        $employees = [
            ['lastname'=>'Abales','firstname'=>'Isidro','middlename'=>'Mehela','extname'=>''],
            ['lastname'=>'Abao','firstname'=>'Felibert ','middlename'=>'Cenia','extname'=>''],
            ['lastname'=>'Abarquez','firstname'=>'Sharon','middlename'=>'Echem','extname'=>''],
            ['lastname'=>'Abarquez','firstname'=>'Jessie ','middlename'=>'Trana','extname'=>''],
            ['lastname'=>'Abarquez','firstname'=>'Virgie','middlename'=>'Abella','extname'=>''],
            ['lastname'=>'Abaton','firstname'=>'Jimmy Jr.','middlename'=>'Sumandig','extname'=>''],
            ['lastname'=>'Abaton','firstname'=>'Jonathan ','middlename'=>'Bayocot','extname'=>''],
            ['lastname'=>'Abaton','firstname'=>'Naome','middlename'=>'Donos','extname'=>''],
            ['lastname'=>'Abaya','firstname'=>'Jaypee ','middlename'=>'Felix','extname'=>''],
            ['lastname'=>'Abrio','firstname'=>'Simplicio ','middlename'=>'Payangga','extname'=>''],
            ['lastname'=>'Abrio','firstname'=>'Chandler','middlename'=>'Licuanan','extname'=>''],
            ['lastname'=>'Abroguena','firstname'=>'Hannah Jean ','middlename'=>'Sagrado','extname'=>''],
            ['lastname'=>'Acil','firstname'=>'Kharren ','middlename'=>'Onahon','extname'=>''],
            ['lastname'=>'Acma','firstname'=>'Allan','middlename'=>'Tacbobo','extname'=>''],
            ['lastname'=>'Acobo','firstname'=>' Elmo ','middlename'=>'Labra','extname'=>''],
            ['lastname'=>'Acuzar','firstname'=>'Cathlyn Jean','middlename'=>'Pulgarinas','extname'=>''],
            ['lastname'=>'Adaptar','firstname'=>'Rahbie','middlename'=>'Bongalos','extname'=>''],
            ['lastname'=>'Agbalog','firstname'=>'Franco Ceasar','middlename'=>'Mercado','extname'=>''],
            ['lastname'=>'Agoy-oy','firstname'=>'Jonathan ','middlename'=>'Decena','extname'=>''],
            ['lastname'=>'Aguanta','firstname'=>'Dante ','middlename'=>'Reazon','extname'=>''],
            ['lastname'=>'Aguilar','firstname'=>'Rani Grace','middlename'=>'Sido','extname'=>''],
            ['lastname'=>'Agura ','firstname'=>'Lorimer ','middlename'=>'Andaya ','extname'=>''],
            ['lastname'=>'Aguro','firstname'=>' Aniza Marie ','middlename'=>'Campong','extname'=>''],
            ['lastname'=>'Ajon','firstname'=>'Helen','middlename'=>'Bentulan','extname'=>''],
            ['lastname'=>'Alavanza','firstname'=>'Jhony','middlename'=>'Saburao','extname'=>''],
            ['lastname'=>'Alay','firstname'=>'Ireneo','middlename'=>'Lagrada','extname'=>''],
            ['lastname'=>'Alcantara','firstname'=>'Erik','middlename'=>'Catubig','extname'=>''],
            ['lastname'=>'Alegado','firstname'=>'Rendy Lou','middlename'=>'Pausanos','extname'=>''],
            ['lastname'=>'Alegado','firstname'=>'Francisco ','middlename'=>'Borromeo','extname'=>''],
            ['lastname'=>'Alfanta ','firstname'=>'Bryankim ','middlename'=>'Cabunoc ','extname'=>''],
            ['lastname'=>'Alimpuangon','firstname'=>'June','middlename'=>'Bahaynon','extname'=>''],
            ['lastname'=>'Alvarado','firstname'=>'Junabelle','middlename'=>'D','extname'=>''],
            ['lastname'=>'Amolat','firstname'=>'amson','middlename'=>'','extname'=>''],
            ['lastname'=>'Amolat','firstname'=>'Rico','middlename'=>'','extname'=>''],
            ['lastname'=>'Anasco','firstname'=>'Alan','middlename'=>'','extname'=>''],
            ['lastname'=>'Anasco','firstname'=>'Charlie ','middlename'=>'Daganato','extname'=>''],
            ['lastname'=>'Anasco','firstname'=>' Stephen','middlename'=>'Madula','extname'=>''],
            ['lastname'=>'Anasco','firstname'=>'Leonardo','middlename'=>'Escabas','extname'=>''],
            ['lastname'=>'Anaya','firstname'=>'Mark June ','middlename'=>'Cella ','extname'=>''],
            ['lastname'=>'Anover','firstname'=>'Karen','middlename'=>'Villamin','extname'=>''],
            ['lastname'=>'Anoza','firstname'=>'Reno','middlename'=>' Ragandap','extname'=>''],
            ['lastname'=>'Anud','firstname'=>'Jonathan','middlename'=>'Bajao','extname'=>''],
            ['lastname'=>'Aquiman','firstname'=>'Vicente','middlename'=>'Lato','extname'=>''],
            ['lastname'=>'Aquino','firstname'=>'Estila ','middlename'=>'Gipolan','extname'=>''],
            ['lastname'=>'Arana','firstname'=>'Richard','middlename'=>'Lee','extname'=>''],
            ['lastname'=>'Arceo','firstname'=>'Sonny Boy','middlename'=>'Dairo','extname'=>''],
            ['lastname'=>'Ardemer','firstname'=>'Cecille Lester ','middlename'=>'Oco','extname'=>''],
            ['lastname'=>'Arienza','firstname'=>'Rio Carlo','middlename'=>'','extname'=>''],
            ['lastname'=>'Arona ','firstname'=>'Ray Mark ','middlename'=>'S. ','extname'=>''],
            ['lastname'=>'Artajo','firstname'=>'Alberto ','middlename'=>'Japitan','extname'=>''],
            ['lastname'=>'Asinero ','firstname'=>'Shelemia ','middlename'=>'Reducto ','extname'=>''],
            ['lastname'=>'Aton ','firstname'=>'Norilyn ','middlename'=>'Bahian ','extname'=>''],
            ['lastname'=>'Ayson ','firstname'=>'Michelle Rae','middlename'=>'Javier ','extname'=>''],
            ['lastname'=>'Baclado','firstname'=>'Jesserial','middlename'=>'Geoca','extname'=>''],
            ['lastname'=>'Baconguis','firstname'=>'Rudy','middlename'=>'Gabitano','extname'=>''],
            ['lastname'=>'Bagotsay','firstname'=>'Ralph','middlename'=>'Abueva','extname'=>''],
            ['lastname'=>'Bahaynon','firstname'=>'Rogelio','middlename'=>'Sambalan','extname'=>''],
            ['lastname'=>'Bahaynon','firstname'=>'Rey ','middlename'=>'Cabulo','extname'=>''],
            ['lastname'=>'Bahaynon','firstname'=>'Rey ','middlename'=>'Aninloy. Jr.','extname'=>''],
            ['lastname'=>'Bajuyo','firstname'=>'Christelle Ann','middlename'=>'Setosta','extname'=>''],
            ['lastname'=>'Balabat','firstname'=>'Carmila','middlename'=>'Dona','extname'=>''],
            ['lastname'=>'Balaod','firstname'=>' Winston Jhon','middlename'=>' Panares','extname'=>''],
            ['lastname'=>'Balbuena','firstname'=>'Benjie ','middlename'=>'Udtohan','extname'=>''],
            ['lastname'=>'Balcos','firstname'=>' Eric','middlename'=>'Alquiza','extname'=>''],
            ['lastname'=>'Balcos ','firstname'=>'Marlon ','middlename'=>'Minoza ','extname'=>''],
            ['lastname'=>'Baldo','firstname'=>'Welendino','middlename'=>'Tagap','extname'=>''],
            ['lastname'=>'Baluran','firstname'=>'Joeddie','middlename'=>'Melig','extname'=>''],
            ['lastname'=>'Banalo','firstname'=>'Alejandro','middlename'=>' Bustamante','extname'=>''],
            ['lastname'=>'Bantilan','firstname'=>'Joselito ','middlename'=>'Baruela','extname'=>''],
            ['lastname'=>'Baran','firstname'=>'Christian Paul','middlename'=>'Torrentira','extname'=>''],
            ['lastname'=>'Baran','firstname'=>'Nino ','middlename'=>'Torrentira','extname'=>''],
            ['lastname'=>'Barrio','firstname'=>'Jervy ','middlename'=>'Credo','extname'=>''],
            ['lastname'=>'Barroa','firstname'=>'Shelaren','middlename'=>'Tutor','extname'=>''],
            ['lastname'=>'Barrogo','firstname'=>'Josue','middlename'=>'Agtina','extname'=>''],
            ['lastname'=>'Baslao','firstname'=>'Ernesto','middlename'=>'Tapdasan','extname'=>''],
            ['lastname'=>'Baston','firstname'=>'Reywel','middlename'=>'Lapisegue','extname'=>''],
            ['lastname'=>'Batasin-in','firstname'=>'Stephen John ','middlename'=>'Dalimoos','extname'=>''],
            ['lastname'=>'Batausa','firstname'=>'Kennedy','middlename'=>'Gonhay','extname'=>''],
            ['lastname'=>'Bautista','firstname'=>'Jumar','middlename'=>'G','extname'=>''],
            ['lastname'=>'Beduya','firstname'=>'Gerard Peter','middlename'=>'O','extname'=>''],
            ['lastname'=>'Bernales','firstname'=>'Maria Agnes ','middlename'=>'Ricaforte','extname'=>''],
            ['lastname'=>'Betanio','firstname'=>'Judito ','middlename'=>'Cabosao','extname'=>''],
            ['lastname'=>'Binayao','firstname'=>'Crispo','middlename'=>'Alaiza','extname'=>''],
            ['lastname'=>'Binayao','firstname'=>'Junie ','middlename'=>'Sumalta','extname'=>''],
            ['lastname'=>'Binayao','firstname'=>'Allan','middlename'=>'Salvan','extname'=>''],
            ['lastname'=>'Binayao','firstname'=>' Corina ','middlename'=>'Alatao','extname'=>''],
            ['lastname'=>'Binayao','firstname'=>'Rogelio ','middlename'=>'Sambalon','extname'=>''],
            ['lastname'=>'Bingcola','firstname'=>'Ruby ','middlename'=>'Edulan','extname'=>''],
            ['lastname'=>'Binongcal','firstname'=>'Rexmar','middlename'=>'Alimbog','extname'=>''],
            ['lastname'=>'Bonita','firstname'=>'Arturo','middlename'=>'Calam','extname'=>''],
            ['lastname'=>'Bontilao','firstname'=>'Ronald ','middlename'=>'Sabangon','extname'=>''],
            ['lastname'=>'Bontilao','firstname'=>'Jeniffrey','middlename'=>'Janoplo','extname'=>''],
            ['lastname'=>'Bontilao','firstname'=>'Rafael','middlename'=>'Janoplo','extname'=>''],
            ['lastname'=>'Bontilao ','firstname'=>'Kenneth ','middlename'=>'Sawan-on ','extname'=>''],
            ['lastname'=>'Botaya','firstname'=>'Gilbert','middlename'=>'Armecin','extname'=>''],
            ['lastname'=>'Braga','firstname'=>'Christopher Jun','middlename'=>'Saguinhon','extname'=>''],
            ['lastname'=>'Budlao','firstname'=>' Emil','middlename'=>'Regular','extname'=>''],
            ['lastname'=>'Buna','firstname'=>'Dorothy ','middlename'=>'Saga','extname'=>''],
            ['lastname'=>'Cabanas','firstname'=>'Warlito','middlename'=>'Care','extname'=>''],
            ['lastname'=>'Cabanas','firstname'=>'Dennis ','middlename'=>'Narvasa','extname'=>''],
            ['lastname'=>'Cabang','firstname'=>'Andric','middlename'=>'Aliwate','extname'=>''],
            ['lastname'=>'Cabonillas','firstname'=>'Anselmo','middlename'=>'Balaba','extname'=>''],
            ['lastname'=>'Cabrera','firstname'=>'Kit Joseph Laurel','middlename'=>'Batad','extname'=>''],
            ['lastname'=>'Cachapero','firstname'=>'Ronald','middlename'=>'Comcom','extname'=>''],
            ['lastname'=>'Caduan','firstname'=>'Limuel','middlename'=>'Talugco','extname'=>''],
            ['lastname'=>'Caguitla','firstname'=>'Nerio','middlename'=>'Alambatin','extname'=>''],
            ['lastname'=>'Cajardo','firstname'=>'Gloria','middlename'=>'Tawagan','extname'=>''],
            ['lastname'=>'Cajilla','firstname'=>'Rolando ','middlename'=>'Madronal','extname'=>''],
            ['lastname'=>'Calisagan','firstname'=>'Raelonda ','middlename'=>'Vega','extname'=>''],
            ['lastname'=>'Calvo','firstname'=>'Sonia','middlename'=>'Tesocan','extname'=>''],
            ['lastname'=>'Campos','firstname'=>'Romnick','middlename'=>'Guinontao','extname'=>''],
            ['lastname'=>'Campos','firstname'=>'Democrito','middlename'=>'Lallodo','extname'=>''],
            ['lastname'=>'Canadilla','firstname'=>'Jemmy ','middlename'=>'Butanas','extname'=>''],
            ['lastname'=>'Cantery','firstname'=>'Taj Jourdan','middlename'=>'Bongcaron','extname'=>''],
            ['lastname'=>'Caringas','firstname'=>'Alicia ','middlename'=>'Siton','extname'=>''],
            ['lastname'=>'Castardo','firstname'=>'Dan ','middlename'=>'Ranoa','extname'=>''],
            ['lastname'=>'Castillon','firstname'=>'Jolito ','middlename'=>'Saga','extname'=>''],
            ['lastname'=>'Catalan','firstname'=>'Fabio','middlename'=>'Villaganas','extname'=>''],
            ['lastname'=>'Cataluna','firstname'=>'Levi ','middlename'=>'Giganto','extname'=>''],
            ['lastname'=>'Cavite','firstname'=>'Mary Joy','middlename'=>'Pequiro','extname'=>''],
            ['lastname'=>'Cenabre','firstname'=>'Clyde Arvy','middlename'=>'Ganas','extname'=>''],
            ['lastname'=>'Ceniza','firstname'=>'Ken Christian','middlename'=>'Pinero','extname'=>''],
            ['lastname'=>'Ching','firstname'=>'Mary Jean','middlename'=>'Celosia','extname'=>''],
            ['lastname'=>'Cleopas','firstname'=>'Ria Mae ','middlename'=>'Secuya ','extname'=>''],
            ['lastname'=>'Cogay','firstname'=>'Ruel','middlename'=>'','extname'=>''],
            ['lastname'=>'Compendio','firstname'=>'Ranin ','middlename'=>'Bagongon','extname'=>''],
            ['lastname'=>'Coquia','firstname'=>'Dominador ','middlename'=>'Cuenca','extname'=>''],
            ['lastname'=>'Coquilla','firstname'=>'Jay Shell ','middlename'=>'Dela Cruz','extname'=>''],
            ['lastname'=>'Cordovez','firstname'=>'Melchor','middlename'=>'Ramo','extname'=>''],
            ['lastname'=>'Cornelio','firstname'=>'Mario','middlename'=>'Pagayao','extname'=>''],
            ['lastname'=>'Corvera','firstname'=>'Julita','middlename'=>'Divinagracia','extname'=>''],
            ['lastname'=>'Credo','firstname'=>'Kent','middlename'=>'Barrio ','extname'=>''],
            ['lastname'=>'Cuerquis','firstname'=>'Arthur ','middlename'=>'Simbajon','extname'=>''],
            ['lastname'=>'Cunado','firstname'=>'Myla','middlename'=>'Angcla','extname'=>''],
            ['lastname'=>'Curato','firstname'=>'Juliet ','middlename'=>'Hipulan','extname'=>''],
            ['lastname'=>'Dacal-Dacal','firstname'=>'Maximo ','middlename'=>' Tabamo','extname'=>''],
            ['lastname'=>'Dadole','firstname'=>'Jerry ','middlename'=>'Entira','extname'=>''],
            ['lastname'=>'Dagandara','firstname'=>'Jimmy ','middlename'=>'Barrientos','extname'=>''],
            ['lastname'=>'Dagunlay','firstname'=>'Crispina ','middlename'=>'Guinayao','extname'=>''],
            ['lastname'=>'Dahe','firstname'=>'Daniel','middlename'=>'','extname'=>''],
            ['lastname'=>'Dahino','firstname'=>'Edith ','middlename'=>'Tinggoy','extname'=>''],
            ['lastname'=>'Dalwatan','firstname'=>'Rhumcyn','middlename'=>'Logronio','extname'=>''],
            ['lastname'=>'Dampal ','firstname'=>'Ma. Theresa  ','middlename'=>'Betinol ','extname'=>''],
            ['lastname'=>'Dandan','firstname'=>' Regie','middlename'=>'Aclao','extname'=>''],
            ['lastname'=>'Dasilao','firstname'=>'Ivan Kristoffer ','middlename'=>'Josue','extname'=>''],
            ['lastname'=>'Data ','firstname'=>'Ivy ','middlename'=>'Galorpe ','extname'=>''],
            ['lastname'=>'Dawat ','firstname'=>'Norlyn ','middlename'=>'Pinara ','extname'=>''],
            ['lastname'=>'Dayle','firstname'=>'Junry ','middlename'=>'Arado','extname'=>''],
            ['lastname'=>'De Asis','firstname'=>'Ela Marie','middlename'=>'Carbon','extname'=>''],
            ['lastname'=>'De La Torre','firstname'=>'Reniefe ','middlename'=>'Baranda','extname'=>''],
            ['lastname'=>'Decena','firstname'=>'Jofel ','middlename'=>'Pausanos','extname'=>''],
            ['lastname'=>'Del Castillo','firstname'=>'Elsie','middlename'=>'Lincodo','extname'=>''],
            ['lastname'=>'Dela Cerna','firstname'=>'Cris ','middlename'=>'Cabonilas','extname'=>''],
            ['lastname'=>'Deones','firstname'=>'Wennysis Michael','middlename'=>'Macaliag','extname'=>''],
            ['lastname'=>'Dilag','firstname'=>'Jovilyn','middlename'=>'Rivero','extname'=>''],
            ['lastname'=>'Dinoy','firstname'=>'Elaine Mae','middlename'=>'Alias','extname'=>''],
            ['lastname'=>'Dinoy','firstname'=>' Hazel  Mae ','middlename'=>'Bulanta','extname'=>''],
            ['lastname'=>'Domo Jr.','firstname'=>'Raymundo ','middlename'=>'Tinga','extname'=>''],
            ['lastname'=>'Dona','firstname'=>'Rodel','middlename'=>'Dao','extname'=>''],
            ['lastname'=>'Donghil','firstname'=>'Nelson','middlename'=>'Adanza','extname'=>''],
            ['lastname'=>'Doverte','firstname'=>'Rey Noel','middlename'=>'Uypala','extname'=>''],
            ['lastname'=>'Duenas','firstname'=>'John Rowe ','middlename'=>'Mateo','extname'=>''],
            ['lastname'=>'Dulfo','firstname'=>'Lotis ','middlename'=>'Panlee','extname'=>''],
            ['lastname'=>'Dumadag','firstname'=>'Hilario','middlename'=>'Limit','extname'=>''],
            ['lastname'=>'Dumaraog','firstname'=>'Devlin','middlename'=>'A','extname'=>''],
            ['lastname'=>'Echem','firstname'=>'Justin ','middlename'=>'Bancale','extname'=>''],
            ['lastname'=>'Eco','firstname'=>'Enrique','middlename'=>' Opada','extname'=>''],
            ['lastname'=>'Edralin','firstname'=>'Cliford','middlename'=>'Abecia','extname'=>''],
            ['lastname'=>'Egama ','firstname'=>'Vanessa Jean ','middlename'=>'Daplin ','extname'=>''],
            ['lastname'=>'Embuscado','firstname'=>'John Eric','middlename'=>'Romeo','extname'=>''],
            ['lastname'=>'Ensencio','firstname'=>'Diosdado','middlename'=>'Doria','extname'=>''],
            ['lastname'=>'Ensencio','firstname'=>'Christian Rhod','middlename'=>'Regis ','extname'=>''],
            ['lastname'=>'Epanto','firstname'=>'Patrick ','middlename'=>'Onahon','extname'=>''],
            ['lastname'=>'Escarro','firstname'=>'Guirdon','middlename'=>'Nacario','extname'=>''],
            ['lastname'=>'Espina','firstname'=>'Vernon ','middlename'=>'Mante','extname'=>''],
            ['lastname'=>'Espinosa. ','firstname'=>'Jay','middlename'=>'Cacho','extname'=>''],
            ['lastname'=>'Estillore','firstname'=>'Isacar ','middlename'=>'Dalapo ','extname'=>''],
            ['lastname'=>'Estoce','firstname'=>'Maria Jeanette','middlename'=>' Bacor','extname'=>''],
            ['lastname'=>'Etulle','firstname'=>'Melima J.','middlename'=>'Guiritan','extname'=>''],
            ['lastname'=>'Fernandez','firstname'=>'Rey Kristian','middlename'=>'Campong','extname'=>''],
            ['lastname'=>'Ferrer','firstname'=>'Rachel','middlename'=>'Concha','extname'=>''],
            ['lastname'=>'Figuracion','firstname'=>'Dexter ','middlename'=>'Lugo','extname'=>''],
            ['lastname'=>'Flaviano','firstname'=>'Jeremie','middlename'=>'Dela Pena','extname'=>''],
            ['lastname'=>'Gabinete','firstname'=>'Julius','middlename'=>'Sumarana','extname'=>''],
            ['lastname'=>'Gabitano','firstname'=>'Julito','middlename'=>'Jacutin','extname'=>''],
            ['lastname'=>'Gabitano','firstname'=>'Lilia ','middlename'=>'Mabalos','extname'=>''],
            ['lastname'=>'Gabor ','firstname'=>'Dhen ','middlename'=>'Piit ','extname'=>''],
            ['lastname'=>'Gabuya','firstname'=>'Renante','middlename'=>'Lukindab','extname'=>''],
            ['lastname'=>'Gairan','firstname'=>'Engrid','middlename'=>'Menesterio','extname'=>''],
            ['lastname'=>'Galleto','firstname'=>'Gabriel  ','middlename'=>'Andaya','extname'=>''],
            ['lastname'=>'Galolo','firstname'=>'Roland Sr.','middlename'=>'Vicariato','extname'=>''],
            ['lastname'=>'Gamay','firstname'=>'Florencio ','middlename'=>'Onahon','extname'=>''],
            ['lastname'=>'Ganiay','firstname'=>'Domino ','middlename'=>'Milleza','extname'=>''],
            ['lastname'=>'Ganzan','firstname'=>'Lourdes','middlename'=>'Salabsab','extname'=>''],
            ['lastname'=>'Ganzan','firstname'=>'Dominador ','middlename'=>'Salbatierra','extname'=>''],
            ['lastname'=>'Garcia Jr.','firstname'=>'Dalfin','middlename'=>'Juarez','extname'=>''],
            ['lastname'=>'Gaspe','firstname'=>'Ivarie Jun ','middlename'=>'Salait','extname'=>''],
            ['lastname'=>'Gayangan','firstname'=>'Lelybeth ','middlename'=>'Sacote','extname'=>''],
            ['lastname'=>'Gayramara','firstname'=>'Ulyses','middlename'=>'Arbues','extname'=>''],
            ['lastname'=>'General','firstname'=>'Ponciano ','middlename'=>'Antiquina Jr.','extname'=>''],
            ['lastname'=>'Gentio','firstname'=>'Aldrin ','middlename'=>'Ello','extname'=>''],
            ['lastname'=>'Gevero','firstname'=>'Fritchar','middlename'=>'Hinayon','extname'=>''],
            ['lastname'=>'Go','firstname'=>'Melodia','middlename'=>'Udtuhan','extname'=>''],
            ['lastname'=>'Goayan','firstname'=>'Ana Marie','middlename'=>'Ching','extname'=>''],
            ['lastname'=>'Goayan','firstname'=>'Eva ','middlename'=>'Abales','extname'=>''],
            ['lastname'=>'Gonhay','firstname'=>'Rodel','middlename'=>'Lumintad','extname'=>''],
            ['lastname'=>'Gozon','firstname'=>'Alexander ','middlename'=>'Jamisola','extname'=>''],
            ['lastname'=>'Gozon','firstname'=>'Allona Jean ','middlename'=>'Yana ','extname'=>''],
            ['lastname'=>'Guinayon','firstname'=>'Rowen','middlename'=>'Leparto','extname'=>''],
            ['lastname'=>'Guitarte','firstname'=>'Ma. Jeneza ','middlename'=>'Collado','extname'=>''],
            ['lastname'=>'Gulanes','firstname'=>'Gwendolyn ','middlename'=>'Plaza','extname'=>''],
            ['lastname'=>'Gumonan','firstname'=>'Kenn Migan','middlename'=>'Casicas','extname'=>''],
            ['lastname'=>'Handayan','firstname'=>'J-son','middlename'=>'Alinob','extname'=>''],
            ['lastname'=>'Hangalay','firstname'=>' Luciano','middlename'=>'Lagaylay','extname'=>''],
            ['lastname'=>'Herocan','firstname'=>'John Rey','middlename'=>'Siclay','extname'=>''],
            ['lastname'=>'Herrera','firstname'=>'Jhoy','middlename'=>'Manuel','extname'=>''],
            ['lastname'=>'Hidalgo ','firstname'=>'Noemi ','middlename'=>'Obgero ','extname'=>''],
            ['lastname'=>'Higyawan','firstname'=>'Norberto ','middlename'=>'Duyasan','extname'=>''],
            ['lastname'=>'Hinampas','firstname'=>'Michael','middlename'=>' Ocho','extname'=>''],
            ['lastname'=>'Hinoyog','firstname'=>'Crispin','middlename'=>'Saguinuay','extname'=>''],
            ['lastname'=>'Ibabao','firstname'=>'Kavin','middlename'=>'Pamiham','extname'=>''],
            ['lastname'=>'Igcalinos','firstname'=>'Aaron','middlename'=>'Cielo','extname'=>''],
            ['lastname'=>'Improgo ','firstname'=>'Ferdinand','middlename'=>'Ami','extname'=>''],
            ['lastname'=>'Inocian','firstname'=>'Sheenajean','middlename'=>'Teologo','extname'=>''],
            ['lastname'=>'Inte','firstname'=>'Nova Mae','middlename'=>' Castor','extname'=>''],
            ['lastname'=>'Ipanag','firstname'=>'Reny','middlename'=>'Jusay','extname'=>''],
            ['lastname'=>'Jabiniao','firstname'=>'Bendilo ','middlename'=>'Babasol','extname'=>''],
            ['lastname'=>'Jaum','firstname'=>'Reynaldo','middlename'=>'Dico','extname'=>''],
            ['lastname'=>'Javier','firstname'=>'Peter','middlename'=>'Navarro','extname'=>''],
            ['lastname'=>'Jayme','firstname'=>'Julina','middlename'=>'Bunayog','extname'=>''],
            ['lastname'=>'Jerusalem','firstname'=>'Argie','middlename'=>'Oliva','extname'=>''],
            ['lastname'=>'Jimeno','firstname'=>'Criselda','middlename'=>'Clima','extname'=>''],
            ['lastname'=>'Jomoc','firstname'=>'Shana Grace ','middlename'=>'Leyson','extname'=>''],
            ['lastname'=>'Jover','firstname'=>'Edmund','middlename'=>' Espina','extname'=>''],
            ['lastname'=>'Juarez','firstname'=>'Ritchel','middlename'=>'Cabaneros','extname'=>''],
            ['lastname'=>'Justol','firstname'=>'Juan','middlename'=>' Margate','extname'=>''],
            ['lastname'=>'Labajo','firstname'=>'Joseph','middlename'=>'Ursal','extname'=>''],
            ['lastname'=>'Labariento','firstname'=>'Julius Michael ','middlename'=>'Onahon','extname'=>''],
            ['lastname'=>'Labe','firstname'=>'Joel ','middlename'=>'Pahilangco','extname'=>''],
            ['lastname'=>'Labial','firstname'=>'Andronico Jr.','middlename'=>'Blanco','extname'=>''],
            ['lastname'=>'Labrado','firstname'=>'Amado','middlename'=>' Logronio','extname'=>''],
            ['lastname'=>'Lacre','firstname'=>'Lolita ','middlename'=>'Tingga','extname'=>''],
            ['lastname'=>'Lacsa','firstname'=>'Mona Liel','middlename'=>'Estacion','extname'=>''],
            ['lastname'=>'Lagaylay','firstname'=>'Bernadith ','middlename'=>'Bacong','extname'=>''],
            ['lastname'=>'Lahayon','firstname'=>'Jerry Jr.','middlename'=>'','extname'=>''],
            ['lastname'=>'Lahayon','firstname'=>'Leo','middlename'=>'C','extname'=>''],
            ['lastname'=>'Lan-ayan','firstname'=>'Gilbert','middlename'=>'Bansalay','extname'=>''],
            ['lastname'=>'Lasaga','firstname'=>'Ronald','middlename'=>'','extname'=>''],
            ['lastname'=>'Lascona','firstname'=>'Michael','middlename'=>' Hinagdanan','extname'=>''],
            ['lastname'=>'Lastimoso','firstname'=>'Romeo','middlename'=>'Layao','extname'=>''],
            ['lastname'=>'Lee','firstname'=>'Yo Chin','middlename'=>'Pailagao','extname'=>''],
            ['lastname'=>'Lerongan','firstname'=>'Daniel','middlename'=>'Sinohot','extname'=>''],
            ['lastname'=>'Leyson','firstname'=>'James Ryan ','middlename'=>'Intong','extname'=>''],
            ['lastname'=>'Limana','firstname'=>'Reina Joy','middlename'=>'Payangga','extname'=>''],
            ['lastname'=>'Linggian','firstname'=>'Ramil','middlename'=>'Noay','extname'=>''],
            ['lastname'=>'Linggian','firstname'=>'Annalou','middlename'=>'Gonzaga','extname'=>''],
            ['lastname'=>'Linohon','firstname'=>'Adrian','middlename'=>'Tomarong','extname'=>''],
            ['lastname'=>'Lipang','firstname'=>'Jet','middlename'=>'Leona','extname'=>''],
            ['lastname'=>'Litohon','firstname'=>'Johmar','middlename'=>'Cariton','extname'=>''],
            ['lastname'=>'Llagas','firstname'=>'Christopher Jayson','middlename'=>'Villad','extname'=>''],
            ['lastname'=>'Logrosa','firstname'=>'Martiniano ','middlename'=>'Bautista','extname'=>''],
            ['lastname'=>'Lompon','firstname'=>'Gheame','middlename'=>'Barrio ','extname'=>''],
            ['lastname'=>'Lompon','firstname'=>'Ferdinand ','middlename'=>'Madula','extname'=>''],
            ['lastname'=>'Lompon','firstname'=>'Jerry  ','middlename'=>'Madula','extname'=>''],
            ['lastname'=>'Lompon','firstname'=>'Jacinto ','middlename'=>'Magpulong','extname'=>''],
            ['lastname'=>'Lontian','firstname'=>'Roseanne ','middlename'=>'Binayao','extname'=>''],
            ['lastname'=>'Lozada','firstname'=>'Jhujhu ','middlename'=>'Radoc','extname'=>''],
            ['lastname'=>'Lucero','firstname'=>'Cristiano','middlename'=>'Quino','extname'=>''],
            ['lastname'=>'Lugmay','firstname'=>'Jiv Darren','middlename'=>'Anlagan','extname'=>''],
            ['lastname'=>'Lumintad','firstname'=>'Sherelyn','middlename'=>'Dela Cerna','extname'=>''],
            ['lastname'=>'Luna','firstname'=>'Concepcion','middlename'=>'Eco','extname'=>''],
            ['lastname'=>'Maantos','firstname'=>'Richard ','middlename'=>'Mangginimba','extname'=>''],
            ['lastname'=>'Maape','firstname'=>'Algerico','middlename'=>'Labandero','extname'=>''],
            ['lastname'=>'Mabalos','firstname'=>'Trinidad','middlename'=>' Hulagpos','extname'=>''],
            ['lastname'=>'Mabulac','firstname'=>'Irene Mae','middlename'=>'Presbitero','extname'=>''],
            ['lastname'=>'Macapobre','firstname'=>'Alma ','middlename'=>'Cleopas','extname'=>''],
            ['lastname'=>'Madjos','firstname'=>'Isidra ','middlename'=>'Guiwanon','extname'=>''],
            ['lastname'=>'Madrid','firstname'=>'Alvin','middlename'=>'Obalobao','extname'=>''],
            ['lastname'=>'Madronero','firstname'=>'Myra ','middlename'=>'Cachapero','extname'=>''],
            ['lastname'=>'Maginsay','firstname'=>'Niemfa Love','middlename'=>'Wahing','extname'=>''],
            ['lastname'=>'Maglasang','firstname'=>'Melvin','middlename'=>'Cabatingan','extname'=>''],
            ['lastname'=>'Malate','firstname'=>'Allan','middlename'=>'Payag','extname'=>''],
            ['lastname'=>'Mana','firstname'=>'Guilermo Jr','middlename'=>'Licuanan','extname'=>''],
            ['lastname'=>'Mancawan','firstname'=>'Norven Eversol ','middlename'=>'Gumatao','extname'=>''],
            ['lastname'=>'Mancawan','firstname'=>'Danilo ','middlename'=>'Lahayon','extname'=>''],
            ['lastname'=>'Mancawan','firstname'=>'John Rashed ','middlename'=>'Lahayon','extname'=>''],
            ['lastname'=>'Mancawan','firstname'=>'Jessie Cris ','middlename'=>'Lahayon','extname'=>''],
            ['lastname'=>'Manilhig','firstname'=>'Lorelyn ','middlename'=>'Autor','extname'=>''],
            ['lastname'=>'Manosa','firstname'=>'Sherly','middlename'=>'Angeles','extname'=>''],
            ['lastname'=>'Manosa','firstname'=>'Reynaldo','middlename'=>'Ompoc','extname'=>''],
            ['lastname'=>'Mante','firstname'=>'Rewina ','middlename'=>'Camugao','extname'=>''],
            ['lastname'=>'Marfa','firstname'=>'Sheila ','middlename'=>'Gomez','extname'=>''],
            ['lastname'=>'Margallo','firstname'=>'Christopher','middlename'=>'Takiang','extname'=>''],
            ['lastname'=>'Markines','firstname'=>'Maria Theresa','middlename'=>'Bentulan','extname'=>''],
            ['lastname'=>'Marturillas','firstname'=>'Rocelyn','middlename'=>'Balo','extname'=>''],
            ['lastname'=>'Masinlay ','firstname'=>'Godofredo ','middlename'=>'Guinibay','extname'=>''],
            ['lastname'=>'Mata','firstname'=>'Apolinaria ','middlename'=>'Enclonar','extname'=>''],
            ['lastname'=>'Medio','firstname'=>'Johnny','middlename'=>'Abala','extname'=>''],
            ['lastname'=>'Mejias','firstname'=>'Marvin','middlename'=>'Gabayeron','extname'=>''],
            ['lastname'=>'Melig','firstname'=>'Quennie Rose ','middlename'=>'Inta','extname'=>''],
            ['lastname'=>'Mencede','firstname'=>'Alonna ','middlename'=>'Pequiro','extname'=>''],
            ['lastname'=>'Minoza','firstname'=>'Ariel','middlename'=>'Panales','extname'=>''],
            ['lastname'=>'Miranda','firstname'=>'Teofany','middlename'=>'','extname'=>''],
            ['lastname'=>'Mirande','firstname'=>'Juvy Ann','middlename'=>'Pangan','extname'=>''],
            ['lastname'=>'Moncado','firstname'=>'Rose','middlename'=>' Guinontao','extname'=>''],
            ['lastname'=>'Monreal','firstname'=>'Glorianne','middlename'=>'Pajara','extname'=>''],
            ['lastname'=>'Montano','firstname'=>'Ronnie','middlename'=>'Benosa','extname'=>''],
            ['lastname'=>'Montefalcon','firstname'=>'Stephen','middlename'=>'Rosales','extname'=>''],
            ['lastname'=>'Morales','firstname'=>'Joshua Martin','middlename'=>'Gabitano','extname'=>''],
            ['lastname'=>'Mugdan ','firstname'=>'Silver John','middlename'=>'Pacolanang','extname'=>''],
            ['lastname'=>'Murillo','firstname'=>'Jhunlou','middlename'=>'Ocday','extname'=>''],
            ['lastname'=>'Musa','firstname'=>'Jane Patrice ','middlename'=>'Uypala','extname'=>''],
            ['lastname'=>'Namoc Jr.','firstname'=>'Faustino','middlename'=>'Castil','extname'=>''],
            ['lastname'=>'Nanale','firstname'=>'Ariel Gee','middlename'=>' Buenaflor','extname'=>''],
            ['lastname'=>'Narvasa','firstname'=>'Jerico ','middlename'=>'Sandal','extname'=>''],
            ['lastname'=>'Navarro','firstname'=>'Del Sheila','middlename'=>'R','extname'=>''],
            ['lastname'=>'Navarro','firstname'=>'Jenny Rose','middlename'=>'Saguran','extname'=>''],
            ['lastname'=>'Navarro','firstname'=>'Mary Grace','middlename'=>'Saguran','extname'=>''],
            ['lastname'=>'Nicor','firstname'=>'Anita','middlename'=>' Libay','extname'=>''],
            ['lastname'=>'Nillama','firstname'=>'Ronel','middlename'=>'Molina','extname'=>''],
            ['lastname'=>'Nioda','firstname'=>'Sheryl ','middlename'=>'Redoblado','extname'=>''],
            ['lastname'=>'Noay','firstname'=>'Arnold','middlename'=>'','extname'=>''],
            ['lastname'=>'Nolasco','firstname'=>'Orlando ','middlename'=>'Apolinar Jr.','extname'=>''],
            ['lastname'=>'Noro','firstname'=>'Ricky','middlename'=>'Barneja','extname'=>''],
            ['lastname'=>'Obalobao','firstname'=>'Evangeline ','middlename'=>'Lico','extname'=>''],
            ['lastname'=>'Obcena','firstname'=>'Rachelle Anne','middlename'=>'Ramos','extname'=>''],
            ['lastname'=>'Oco','firstname'=>'Chris Albert  ','middlename'=>'Paler','extname'=>''],
            ['lastname'=>'Oguimas','firstname'=>'Charlyn','middlename'=>'Boyles','extname'=>''],
            ['lastname'=>'Olavides','firstname'=>'Airen','middlename'=>' Carreon','extname'=>''],
            ['lastname'=>'Ompad ','firstname'=>'Jovanni ','middlename'=>'Jabon ','extname'=>''],
            ['lastname'=>'Onahon','firstname'=>'Nickarter ','middlename'=>'Jacang','extname'=>''],
            ['lastname'=>'Onahon','firstname'=>'Shyrel Hope','middlename'=>'Bactol','extname'=>''],
            ['lastname'=>'Onahon','firstname'=>'Mary Jane','middlename'=>' Lahayon','extname'=>''],
            ['lastname'=>'Opiso','firstname'=>'Gil','middlename'=>'Mansequioa','extname'=>''],
            ['lastname'=>'Opiso','firstname'=>'Fulgent','middlename'=>'Patron','extname'=>''],
            ['lastname'=>'Ople','firstname'=>'Romeo','middlename'=>'Pelayo','extname'=>''],
            ['lastname'=>'Orlina','firstname'=>'Rezie ','middlename'=>'Epanto','extname'=>''],
            ['lastname'=>'Paca','firstname'=>'Erwin ','middlename'=>'Buenavista','extname'=>''],
            ['lastname'=>'Paca','firstname'=>'Sheena Mae','middlename'=>'','extname'=>''],
            ['lastname'=>'Paca','firstname'=>'Marlon ','middlename'=>'Bayanban','extname'=>''],
            ['lastname'=>'Paca','firstname'=>'Jessel Joy','middlename'=>'Castro','extname'=>''],
            ['lastname'=>'Padayao','firstname'=>' Lope ','middlename'=>'Abelima','extname'=>''],
            ['lastname'=>'Padayon','firstname'=>'Marcelina','middlename'=>'Silaya','extname'=>''],
            ['lastname'=>'Pagente ','firstname'=>'Jessel ','middlename'=>'Nacario ','extname'=>''],
            ['lastname'=>'Pagutayao','firstname'=>'Gaudioso','middlename'=>'','extname'=>''],
            ['lastname'=>'Pajara','firstname'=>'Michael Angelo','middlename'=>'Verana','extname'=>''],
            ['lastname'=>'Pajaron','firstname'=>'John Andrew','middlename'=>'G','extname'=>''],
            ['lastname'=>'Palomar ','firstname'=>'Catherine ','middlename'=>'Ubatay','extname'=>''],
            ['lastname'=>'Panique','firstname'=>'Misty Lee','middlename'=>'A','extname'=>''],
            ['lastname'=>'Panistante','firstname'=>'Charlin','middlename'=>' Datoy','extname'=>''],
            ['lastname'=>'Pantonial','firstname'=>'Marlone','middlename'=>'Jangao','extname'=>''],
            ['lastname'=>'Pardillo','firstname'=>'Leonora','middlename'=>'Bustamante','extname'=>''],
            ['lastname'=>'Parilla','firstname'=>'Marco','middlename'=>'Cagata','extname'=>''],
            ['lastname'=>'Paurillo','firstname'=>'Michael ','middlename'=>'Waslo','extname'=>''],
            ['lastname'=>'Perez','firstname'=>'Gemma','middlename'=>'Oracion','extname'=>''],
            ['lastname'=>'Pojas','firstname'=>'Zeanna Kasandra','middlename'=>'Mondilla','extname'=>''],
            ['lastname'=>'Pradia','firstname'=>'Jona Baldo','middlename'=>'Baldo','extname'=>''],
            ['lastname'=>'Prudenciado','firstname'=>'Diego','middlename'=>'Gayonan','extname'=>''],
            ['lastname'=>'Pulgo','firstname'=>'Christine ','middlename'=>'Demata','extname'=>''],
            ['lastname'=>'Quieta ','firstname'=>'Darrell Mae ','middlename'=>'Anasco ','extname'=>''],
            ['lastname'=>'Quinlog','firstname'=>' Geronimo ','middlename'=>'Abos','extname'=>''],
            ['lastname'=>'Quinlog','firstname'=>'Kobe','middlename'=>'Caylan','extname'=>''],
            ['lastname'=>'Quino','firstname'=>'Agustin ','middlename'=>'Bayantong','extname'=>''],
            ['lastname'=>'Quino','firstname'=>'Manilyn','middlename'=>'','extname'=>''],
            ['lastname'=>'Quino','firstname'=>'Elvin ','middlename'=>'Abrio','extname'=>''],
            ['lastname'=>'Quino','firstname'=>'Archie','middlename'=>'Lompon','extname'=>''],
            ['lastname'=>'Quino','firstname'=>'Reuben','middlename'=>'Pinote','extname'=>''],
            ['lastname'=>'Quipanes','firstname'=>'Teddy ','middlename'=>'Medrina','extname'=>''],
            ['lastname'=>'Rada','firstname'=>'Anna Paula Mae','middlename'=>'Alagon','extname'=>''],
            ['lastname'=>'Ragandang','firstname'=>'Ma. Cassadra','middlename'=>'Araneta','extname'=>''],
            ['lastname'=>'Ragodos','firstname'=>'Democrito','middlename'=>'Rapayla','extname'=>''],
            ['lastname'=>'Ramole','firstname'=>'Arnulfo ','middlename'=>'Hintoy','extname'=>''],
            ['lastname'=>'Ranas','firstname'=>'Myla ','middlename'=>'Ganas','extname'=>''],
            ['lastname'=>'Rances','firstname'=>'Frijie Kim','middlename'=>'Lunas','extname'=>''],
            ['lastname'=>'Rara','firstname'=>'Samatha Grace','middlename'=>'Baldo','extname'=>''],
            ['lastname'=>'Rato','firstname'=>'Johny','middlename'=>'Pasco','extname'=>''],
            ['lastname'=>'Raut-Raut','firstname'=>'Sonny','middlename'=>'Inandam','extname'=>''],
            ['lastname'=>'Razalo','firstname'=>' Genevieve','middlename'=>'Linombay','extname'=>''],
            ['lastname'=>'Reazon','firstname'=>'Jerson','middlename'=>' Oblina','extname'=>''],
            ['lastname'=>'Registos','firstname'=>'Alberto','middlename'=>'Cadinas','extname'=>''],
            ['lastname'=>'Repel','firstname'=>'Zyrin','middlename'=>'Flores','extname'=>''],
            ['lastname'=>'Restificar','firstname'=>'Irish Gay','middlename'=>'Abas','extname'=>''],
            ['lastname'=>'Retuya','firstname'=>'Faith ','middlename'=>'Dahiyag','extname'=>''],
            ['lastname'=>'Reuyan','firstname'=>' Vincent','middlename'=>'Cataquiz','extname'=>''],
            ['lastname'=>'Revilla','firstname'=>'Jorame ','middlename'=>'Duenas','extname'=>''],
            ['lastname'=>'Ricaforte','firstname'=>'Francis','middlename'=>'','extname'=>''],
            ['lastname'=>'Rivel','firstname'=>'Rommel','middlename'=>'Okinlay','extname'=>''],
            ['lastname'=>'Romolu','firstname'=>'Winston','middlename'=>'Orong','extname'=>''],
            ['lastname'=>'Sabana','firstname'=>'Jefferson','middlename'=>'Enloran','extname'=>''],
            ['lastname'=>'Sabit','firstname'=>'Sharah Luz','middlename'=>'Arienza','extname'=>''],
            ['lastname'=>'Sadio','firstname'=>'Baltazar','middlename'=>'Cabanday','extname'=>''],
            ['lastname'=>'Saguilongan','firstname'=>'Belinda ','middlename'=>'Fernando','extname'=>''],
            ['lastname'=>'Saguinod','firstname'=>'Roen','middlename'=>'Gomonan','extname'=>''],
            ['lastname'=>'Salabsab','firstname'=>'Ariel ','middlename'=>'Estillore','extname'=>''],
            ['lastname'=>'Salait','firstname'=>'Agricelo','middlename'=>'Lugnasan','extname'=>''],
            ['lastname'=>'Salon','firstname'=>'Jeanne','middlename'=>' Valle','extname'=>''],
            ['lastname'=>'Salon','firstname'=>'Jemmy','middlename'=>'Taron','extname'=>''],
            ['lastname'=>'Salvador','firstname'=>'Vincent ','middlename'=>'Emboy','extname'=>''],
            ['lastname'=>'Sambalon','firstname'=>'Vivencio','middlename'=>'Mamatan','extname'=>''],
            ['lastname'=>'Samuya','firstname'=>'Edilberto ','middlename'=>'Lagumbay','extname'=>''],
            ['lastname'=>'Sanchez','firstname'=>'Anthony','middlename'=>'Delmo','extname'=>''],
            ['lastname'=>'Sanchez','firstname'=>'Danny ','middlename'=>'Sacatani','extname'=>''],
            ['lastname'=>'Santillan','firstname'=>'Jeonard','middlename'=>'Trosa','extname'=>''],
            ['lastname'=>'Saponon','firstname'=>'Samuel','middlename'=>'Abol','extname'=>''],
            ['lastname'=>'Sawa-on','firstname'=>'Brian','middlename'=>'Alfiler','extname'=>''],
            ['lastname'=>'Sayongan','firstname'=>'Zaldy Jr.','middlename'=>'Ganado','extname'=>''],
            ['lastname'=>'Secuya','firstname'=>'Hilario','middlename'=>'Tahones','extname'=>''],
            ['lastname'=>'Secuya','firstname'=>'Cresensia ','middlename'=>'Mag-aso','extname'=>''],
            ['lastname'=>'Serrano','firstname'=>'Belbeth','middlename'=>'Suralta','extname'=>''],
            ['lastname'=>'Sia','firstname'=>'Mechealle ','middlename'=>'Lompon','extname'=>''],
            ['lastname'=>'Sibillia','firstname'=>'Jonathan','middlename'=>' Contiberos','extname'=>''],
            ['lastname'=>'Sibulon','firstname'=>'Jemuel ','middlename'=>'Alangan','extname'=>''],
            ['lastname'=>'Siclay','firstname'=>'Jonarad ','middlename'=>'Aluto','extname'=>''],
            ['lastname'=>'Silvino','firstname'=>'Ronald Allan  ','middlename'=>'Tandingco','extname'=>''],
            ['lastname'=>'Sinodlay','firstname'=>'Arlita ','middlename'=>'Daman','extname'=>''],
            ['lastname'=>'Siton','firstname'=>'Richard','middlename'=>'Oliva','extname'=>''],
            ['lastname'=>'Soco','firstname'=>'Nelvie','middlename'=>'Calcueva','extname'=>''],
            ['lastname'=>'Solde','firstname'=>'Karren','middlename'=>'Erana','extname'=>''],
            ['lastname'=>'Sonquipal','firstname'=>'Iraida ','middlename'=>'Yecyec','extname'=>''],
            ['lastname'=>'Soriano','firstname'=>'John Rey ','middlename'=>'Abella','extname'=>''],
            ['lastname'=>'Sulinta','firstname'=>'Marlou','middlename'=>' Dinlay','extname'=>''],
            ['lastname'=>'Sumalpong','firstname'=>'Rogelio','middlename'=>'Vega','extname'=>''],
            ['lastname'=>'Sumalta','firstname'=>'Michael  Eric','middlename'=>'Amor','extname'=>''],
            ['lastname'=>'Sumalta Jr.','firstname'=>'Noel ','middlename'=>'Lugtanan','extname'=>''],
            ['lastname'=>'Sumampong','firstname'=>'Aaron','middlename'=>'Binayao','extname'=>''],
            ['lastname'=>'Sumandig','firstname'=>'Jerry ','middlename'=>'Tiburcio','extname'=>''],
            ['lastname'=>'Sumandig','firstname'=>'Jeffrey','middlename'=>'Abaton','extname'=>''],
            ['lastname'=>'Sumandig','firstname'=>'Eva','middlename'=>'Abaton','extname'=>''],
            ['lastname'=>'Sumihay','firstname'=>'Angelo U.','middlename'=>'Ugtalon','extname'=>''],
            ['lastname'=>'Tabaco','firstname'=>'Cristine','middlename'=>'Salvador','extname'=>''],
            ['lastname'=>'Tabiliran','firstname'=>'Geneva','middlename'=>'Regis ','extname'=>''],
            ['lastname'=>'Taclin Jr.','firstname'=>'Constancio','middlename'=>'Nanay','extname'=>''],
            ['lastname'=>'Tagadiad','firstname'=>'Dexter ','middlename'=>'Ihbalic','extname'=>''],
            ['lastname'=>'Taglinao','firstname'=>'Noel','middlename'=>'Arquiza','extname'=>''],
            ['lastname'=>'Tagud','firstname'=>'Garrion','middlename'=>'Rosopan','extname'=>''],
            ['lastname'=>'Tairos','firstname'=>'Mariel Jaime','middlename'=>'Jaime','extname'=>''],
            ['lastname'=>'Talibong','firstname'=>'Tarah Arianne ','middlename'=>'Oliver','extname'=>''],
            ['lastname'=>'Tamula','firstname'=>' Brian ','middlename'=>'Sarong','extname'=>''],
            ['lastname'=>'Tan','firstname'=>'Marian Agnes','middlename'=>'Badelic','extname'=>''],
            ['lastname'=>'Tangub','firstname'=>' Rolando ','middlename'=>'Bendanillo','extname'=>''],
            ['lastname'=>'Terrado','firstname'=>'Jayson','middlename'=>'Maique','extname'=>''],
            ['lastname'=>'Tinay','firstname'=>'Althea Guila','middlename'=>' Asarez','extname'=>''],
            ['lastname'=>'Tingga','firstname'=>'Golden Fe','middlename'=>'R','extname'=>''],
            ['lastname'=>'Tion','firstname'=>' Lydia','middlename'=>'Talugco','extname'=>''],
            ['lastname'=>'Tolentino','firstname'=>'Josephine','middlename'=>' Amper','extname'=>''],
            ['lastname'=>'Tolero','firstname'=>'Fedila','middlename'=>' Makinano','extname'=>''],
            ['lastname'=>'Tonacao','firstname'=>'Asan ','middlename'=>'Baterna','extname'=>''],
            ['lastname'=>'Toquib','firstname'=>'Ariel','middlename'=>'Negrido','extname'=>''],
            ['lastname'=>'Totungan','firstname'=>'Dilmark','middlename'=>'','extname'=>''],
            ['lastname'=>'Travero','firstname'=>'Arnel ','middlename'=>'Sembrano','extname'=>''],
            ['lastname'=>'Tudtud','firstname'=>'Rolando ','middlename'=>'Quino','extname'=>''],
            ['lastname'=>'Uayan','firstname'=>'Rogelio','middlename'=>' Lascuna','extname'=>''],
            ['lastname'=>'Ubagan','firstname'=>'Ariel','middlename'=>'Andilan','extname'=>''],
            ['lastname'=>'Ugtalon','firstname'=>'Cambejune','middlename'=>' Basinay','extname'=>''],
            ['lastname'=>'Uyanguren','firstname'=>'Danny','middlename'=>'','extname'=>''],
            ['lastname'=>'Valdehuesa','firstname'=>'Jasmin','middlename'=>' Embolode','extname'=>''],
            ['lastname'=>'Veloso','firstname'=>'FelIx Sr.','middlename'=>'Dumala','extname'=>''],
            ['lastname'=>'Verdejo','firstname'=>'Ramer ','middlename'=>'Nagac','extname'=>''],
            ['lastname'=>'Verzon','firstname'=>'Josephine ','middlename'=>'Obsioma','extname'=>''],
            ['lastname'=>'Viceda','firstname'=>'Moises Jay','middlename'=>'Sangcay','extname'=>''],
            ['lastname'=>'Victoria','firstname'=>'Louela ','middlename'=>'Gaid','extname'=>''],
            ['lastname'=>'Villanueva','firstname'=>' John Regie','middlename'=>' Evardo','extname'=>''],
            ['lastname'=>'Villegas','firstname'=>'Charlou','middlename'=>'Abobo','extname'=>''],
            ['lastname'=>'Viola','firstname'=>'Junfrix','middlename'=>'Ompoc','extname'=>''],
            ['lastname'=>'Viola','firstname'=>'Loreto','middlename'=>' Pagulong','extname'=>''],
            ['lastname'=>'Virador','firstname'=>'Elbert Franz','middlename'=>'Dela Cruz','extname'=>''],
            ['lastname'=>'Virador','firstname'=>'Emelio','middlename'=>'Juyad','extname'=>''],
            ['lastname'=>'Virador','firstname'=>'Carlito','middlename'=>'Gallogo','extname'=>''],
            ['lastname'=>'Ybanez','firstname'=>'Ronaldo ','middlename'=>'Neri','extname'=>''],
            ['lastname'=>'Yu','firstname'=>' Darwel ','middlename'=>'Paca','extname'=>''],
            ['lastname'=>'Yunker','firstname'=>'Merasol','middlename'=>'Payonda','extname'=>''],
            ['lastname'=>'Zambrano','firstname'=>'Mariano Jr.','middlename'=>'','extname'=>''],
        ];

        foreach($employees as $employee){

            $newemployee = new Employee;

            $newemployee->lastname = $employee['lastname'];
            $newemployee->firstname = $employee['firstname'];
            $newemployee->middlename= $employee['middlename'];
            $newemployee->extname= $employee['extname'];
            $newemployee->save();

            $this->setDeductions($newemployee->id);
        }
    }
}
